Add routes for time-to-first-byte stats
filecoin-station/spark-stats pull request #281
Opened 2024-12-24 13:24 UTC by pyropy

Adds routes for fetching global and per miner time to first byte stats.

Related to https://github.com/space-meridian/roadmap/issues/208

2025-01-05 21:51 UTC, juliangruber requested changes

2025-01-05 21:51 UTC, juliangruber commented on stats/lib/handler.js
> +  fetchDailyRetrievalTimes,
"Retrieval times" isn't self explanatory - it could for example also be the timestamps at which retrievals have been attempted. What about this?

```suggestion
  fetchDailyRetrievalTimings,
```

2025-01-05 21:51 UTC, juliangruber commented on stats/lib/handler.js
> +  fetchDailyRetrievalTimes,
See for example chrome dev tools also using "timings":

<img width="776" alt="Screenshot 2025-01-05 at 22 43 59" src="https://github.com/user-attachments/assets/60a941b4-af43-4ca0-b2d5-e452e214779f" />

2025-01-05 21:51 UTC, juliangruber commented on stats/lib/stats-fetchers.js
> +      percentile_cont(0.5) WITHIN GROUP (ORDER BY time_to_first_byte_p50) AS ttfb_p50
Having variables `time_to_first_byte_p50` and `ttfb_p50` is confusing, as the names don't tell us how they differ. Can you think of a more semantic name for the computed column?

2025-01-09 07:46 UTC, bajtos commented on stats/lib/stats-fetchers.js
> +      percentile_cont(0.5) WITHIN GROUP (ORDER BY time_to_first_byte_p50) AS ttfb_p50
There are two aspects to consider:

1. What name do we want to use in the SQL query?
2. What property name do we want to use in the response body?

Also, note that a p50 value calculated from a list of p50 values is not a true global p50 value; it's just an approximation we decided to use to keep this initial implementation simple.

In that light, I propose to use the name `ttfb` in the response.

```json
[
  { "day": "2025-01-08", "ttfb": 850 }
  { "day": "2025-01-09", "ttfb": 930 }
]
```

I think this name works well for the SQL query, too, but I don't mind using a different name there.

2025-01-09 07:53 UTC, bajtos commented on stats/lib/stats-fetchers.js
> +      percentile_cont(0.5) WITHIN GROUP (ORDER BY time_to_first_byte_p50) AS ttfb_p50
`percentile_cont` returns a double precision floating number, e.g. `20.124`. This is likely to create a sense of false precision.

Let's convert the number to an integer, e.g. using the Postgres `CEIL()` function.

- We could also use `ROUND()` (10.2→10, 10.8→11), but I prefer to be conservative in what we produce and prefer to report slightly worse TTFB values rather than slightly better values.

This is a minor detail, though - I am fine with any rounding function. 

What's important to me is to produce integer values (number of milliseconds), since that's the precision we are getting from the checker ndoes.

2025-01-09 07:54 UTC, bajtos commented on stats/lib/stats-fetchers.js
> +      percentile_cont(0.5) WITHIN GROUP (ORDER BY time_to_first_byte_p50) AS ttfb_p50
One more idea to consider - should we encode the unit (milliseconds) in the property name?

```json
[
  { "day": "2025-01-08", "ttfb_ms": 850 }
  { "day": "2025-01-09", "ttfb_ms": 930 }
]
```

2025-01-09 10:04 UTC, juliangruber commented on stats/lib/stats-fetchers.js
> +      percentile_cont(0.5) WITHIN GROUP (ORDER BY time_to_first_byte_p50) AS ttfb_p50
`"ttfb_ms"` lgtm!

2025-01-09 12:55 UTC, bajtos commented on stats/lib/handler.js
> +  fetchDailyRetrievalTimes,
+1 to use `timings`

2025-01-13 13:07 UTC, pyropy commented on stats/lib/handler.js
> +  fetchDailyRetrievalTimes,
Thanks for suggestion. I have renamed everything from `times` to `timings` including table, routes and functions.

2025-01-13 13:16 UTC, pyropy commented on stats/lib/stats-fetchers.js
> +      percentile_cont(0.5) WITHIN GROUP (ORDER BY time_to_first_byte_p50) AS ttfb_p50
I have missed this as I was testing using round int values. I have added rounding to queries and we're now also rounding computed p50 values before inserting them to the database (in both cases we're rounding using ceil).

I am going to change tests in https://github.com/filecoin-station/spark-evaluate/pull/434 to include more odd values.

2025-01-14 09:39 UTC, pyropy commented
I am marking this ready for review, although CI will fail before https://github.com/filecoin-station/spark-evaluate/pull/434 gets merged.

2025-01-14 12:10 UTC, bajtos commented on stats/test/handler.test.js
> +          '/miner/f1one/retrieval-timings/summary?from=2024-01-10&to=2024-01-20',
IIRC, we use `/summary` for endpoints returning aggregated data over the entire interval. This route returns data for each day within the interval. I propose to rename the route to `/miner/:id/retrieval-timings/daily`.

2025-01-14 12:13 UTC, bajtos approved these changes
LGTM 👍🏻

2025-01-14 14:43 UTC, merged